services:
  mongo_db:
    image: 'mongo:latest'
    restart: unless-stopped
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME'
      - 'MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD'
    ports:
      - '27017:27017'
    volumes:
      - 'db:/data/db'

volumes:
  db: