services:
  mongo_db:
    image: "mongo:latest"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - "db:/data/db"

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-jdk-17
    privileged: true
    user: root
    ports:
      - "9090:9090"
      - "50000:50000"
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker-setup.sh:/usr/local/bin/docker-setup.sh"
    environment:
      - JENKINS_OPTS=--httpPort=9090
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    restart: unless-stopped
    labels:
      org.springframework.boot.ignore: true
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "/usr/local/bin/docker-setup.sh && /usr/local/bin/jenkins.sh",
      ]

volumes:
  db:
  jenkins_home:
