services:
  mongo_db:
    image: "mongo:latest"
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DEV_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DEV_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
