services:
  mongo_db:
    image: "mongo:latest"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - "db:/data/db"

  jenkins:
    image: jenkins/jenkins:jdk17
    ports:
      - "9090:9090"
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent

volumes:
  db:
  jenkins_home:
