services:
  mongo_db:
    image: "mongo:latest"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - "db:/data/db"
    mem_limit: 2g
    cpus: 1.0

  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_GID: "998"
    container_name: jenkins-master
    ports:
      - "9090:9090"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    environment:
      JENKINS_OPTS: "--httpPort=9090"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    labels:
      org.springframework.boot.ignore: true
    privileged: true
    user: root
    mem_limit: 4g
    cpus: 2.0

volumes:
  db:
  jenkins_home:
