FROM openjdk:17-jdk-slim

WORKDIR /app

RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*

COPY pom.xml /app/

RUN mvn dependency:go-offline -B

COPY . /app/

CMD ["mvn", "spring-boot:run"]